/*
 * Conveyer_config.h
 *
 *  Created on: Jan 27, 2021
 *      Author: Mohamed  Ebead
 */

#ifndef CONVEYER_CONFIG_H_
#define CONVEYER_CONFIG_H_



#define CONVEYER_IN_FORWARD_PORT  	 GPIOA
#define CONVEYER_IN_FORWARD_PIN      GPIO_PIN_NO_0

#define CONVEYER_IN_REVERSE_PORT  	 GPIOA
#define CONVEYER_IN_REVERSE_PIN      GPIO_PIN_NO_1

#define CONVEYER_IN_STOP_PORT  		 GPIOA
#define CONVEYER_IN_STOP_PIN         GPIO_PIN_NO_2


#define CONVEYER_OUT_FORWARD_PORT  	GPIOA
#define CONVEYER_OUT_FORWARD_PIN    GPIO_PIN_NO_3

#define CONVEYER_OUT_REVERSE_PORT  	GPIOA
#define CONVEYER_OUT_REVERSE_PIN    GPIO_PIN_NO_4

#define CONVEYER_OUT_STOP_PORT  	GPIOA
#define CONVEYER_OUT_STOP_PIN       GPIO_PIN_NO_5










#endif /* CONVEYER_CONFIG_H_ */






